#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

library.group=com.mudita
library.artifactId=MMD
library.namespace=com.mudita.mmd
library.compileSdk=34
library.minSdk=28
library.targetSdk=34
library.version=1.0.0
